INSERT INTO `stratagem` (`name`, `image`, `type`, `currency`, `cost`, `unlock_level`)
VALUES
-- Support Weapons
('MG-43 Machine Gun', 'Machine_Gun_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 0, 1),
('APW-1 Anti-Materiel Riffle', 'Anti-Materiel_Rifle_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 5000, 1),
('M-105 Stalwart', 'Stalwart_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 3500, 1),
('EAT-17 Expendable Anti-Tank', 'Expendable_Anti-Tank_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 3000, 3),
('GR-8 Recoilless Rifle', 'Recoilless_Rifle_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 6000, 5),
('FLAM-40 Flamethrower', 'Flamethrower_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 6000, 10),
('AC-8 Autocannon', 'Autocannon_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 7000, 10),
('MG-206 Heavy Machine Gun', 'Heavy_Machine_Gun_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 6000, 12),
('RL-77 Airburst Rocket Launcher', 'RL-77_Airburst_Rocket_Launcher_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 8000, 15),
('MLS-4X Commando', 'Commando_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 8000, 15),
('RS-422 Railgun', 'Railgun_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 10000, 20),
('FAF-14 Spear', 'Spear_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 9000, 20),
('StA-X3 W.A.S.P. Launcher', 'StA-X3_W.A.S.P._Launcher_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 12000, 20),
('GL-21 Grenade Launcher', 'Grenade_Launcher_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 6000, 5),
('LAS-98 Laser Cannon', 'Laser_Cannon_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 4000, 5),
('ARC-3 Arc Thrower', 'Arc_Thrower_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 7000, 15),
('LAS-99 Quasar Cannon', 'Quasar_Cannon_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'REQUISITION_SLIPS', 7500, 18),
('TX-41 Sterilizer', 'Sterilizer_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'MEDALS', 85, 0),
('CQC-1 One True Flag', 'CQC-1_One_True_Flag_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'MEDALS', 110, 0),
('GL-52 De-Escalator', 'GL-52_De-Escalator_Stratagem_Icon.webp', 'SUPPORT_WEAPON', 'MEDALS', 85, 0),
-- Offensive
('Orbital Gatling Barrage', 'Orbital_Gatling_Barrage_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 1500, 1),
('Orbital Airburst Strike', 'Orbital_Airburst_Strike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 4000, 5),
('Orbital 120mm HE Barrage', 'Orbital_120mm_HE_Barrage_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 4000, 5),
('Orbital 380mm HE Barrage', 'Orbital_380mm_HE_Barrage_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 7500, 8),
('Orbital Walking Barrage', 'Orbital_Walking_Barrage_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 7500, 10),
('Orbital Laser', 'Orbital_Laser_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 10000, 15),
('Orbital Napalm Barrage', 'Orbital_Napalm_Barrage_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 10000, 18),
('Orbital Railcannon Strike', 'Orbital_Railcannon_Strike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 10000, 20),
('Eagle Strafing Run', 'Eagle_Strafing_Run_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 1500, 1),
('Eagle Airstrike', 'Eagle_Airstrike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 4000, 1),
('Eagle Cluster Bomb', 'Eagle_Cluster_Bomb_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 4000, 3),
('Eagle Napalm Airstrike', 'Eagle_Napalm_Airstrike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 5000, 5),
('Eagle Smoke Strike', 'Eagle_Smoke_Strike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 4000, 8),
('Eagle 110mm Rocket Pods', 'Eagle_110mm_Rocket_Pods_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 7500, 10),
('Eagle 500kg Bomb', 'Eagle_500kg_Bomb_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 10000, 15),
('Orbital Precision Strike', 'Orbital_Precision_Strike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 0, 1),
('Orbital Gas Strike', 'Orbital_Gas_Strike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 4000, 1),
('Orbital EMS Strike', 'Orbital_EMS_Strike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 6000, 5),
('Orbital Smoke Strike', 'Orbital_Smoke_Strike_Stratagem_Icon.webp', 'OFFENSIVE', 'REQUISITION_SLIPS', 4000, 8),
-- Backpack
('LIFT-850 Jump Pack', 'Jump_Pack_Stratagem_Icon.webp', 'BACKPACK', 'REQUISITION_SLIPS', 6000, 8),
('B-1 Supply Pack', 'Supply_Pack_Stratagem_Icon.webp', 'BACKPACK', 'REQUISITION_SLIPS', 4000, 1),
('AX/LAS-5 "Guard Dog" Rover', 'Guard_Dog_Rover_Stratagem_Icon.webp', 'BACKPACK', 'REQUISITION_SLIPS', 7500, 10),
('SH-20 Ballistic Shield Backpack', 'Ballistic_Shield_Backpack_Stratagem_Icon.webp', 'BACKPACK', 'REQUISITION_SLIPS', 6000, 12),
('SH-32 Shield Generator Pack', 'Shield_Generator_Pack_Stratagem_Icon.webp', 'BACKPACK', 'REQUISITION_SLIPS', 10000, 20),
('AX/AR-23 "Guard Dog"', 'Guard_Dog_Stratagem_Icon.webp', 'BACKPACK', 'REQUISITION_SLIPS', 7500, 10),
('AX/ARC-3 "Guard Dog" K-9', 'AX_ARC-3__Guard_Dog__K-9_Stratagem_Icon.webp', 'BACKPACK', 'MEDALS', 110, 10),
('AX/TX-13 "Guard Dog" Dog Breath', 'Guard_Dog_Dog_Breath_Stratagem_Icon.webp', 'BACKPACK', 'MEDALS', 110, 0),
('SH-51 Directional Shield', 'SH-51_Directional_Shield_Stratagem_Icon.webp', 'BACKPACK', 'MEDALS', 75, 0),
('B-100 Portable Hellbomb', 'Portable_Hellbomb_Stratagem_Icon.webp', 'BACKPACK', 'MEDALS', 110, 0),
('LIFT-860 Hover Pack', 'Hover_Pack_Stratagem_Icon.webp', 'BACKPACK', 'MEDALS', 110, 0),
-- Defensive
('E/MG-101 HMG Emplacement', 'HMG_Emplacement_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 10000, 10),
('FX-12 Shield Generator Relay', 'Shield_Generator_Relay_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 9000, 10),
('A/ARC-3 Tesla Tower', 'Tesla_Tower_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 8000, 15),
('E/GL-21 Grenadier Battlement', 'GL-21_Grenadier_Battlement_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 10000, 15),
('MD-6 Anti-Personnel Minefield', 'Anti-Personnel_Minefield_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 1500, 1),
('MD-I4 Incendiary Mines', 'Incendiary_Mines_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 4000, 8),
('MD-17 Anti-Tank Mines', 'MD-17_Anti-Tank_Mines_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 7000, 15),
('MD-8 Gas Mines', 'Gas_Minefield_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 12000, 20),
('A/MG-43 Machine Gun Sentry', 'Machine_Gun_Sentry_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 1500, 1),
('A/G-16 Gatling Sentry', 'Gatling_Sentry_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 4000, 5),
('A/M-12 Mortar Sentry', 'Mortar_Sentry_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 7000, 8),
('A/AC-8 Autocannon Sentry', 'Autocannon_Sentry_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 6000, 13),
('A/MLS-4X Rocket Sentry', 'Rocket_Sentry_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 7500, 15),
('A/M-23 EMS Mortar Sentry', 'AM-23_EMS_Mortar_Sentry_Stratagem_Icon.webp', 'DEFENSIVE', 'REQUISITION_SLIPS', 8000, 20),
('E/AT-12 Anti-Tank Emplacement', 'E_AT-12_Anti-Tank_Emplacement_Stratagem_Icon.webp', 'DEFENSIVE', 'MEDALS', 110, 0),
('A/FLAM-40 Flame Sentry', 'A_FLAM-40_Flame_Sentry_Stratagem_Icon.webp', 'DEFENSIVE', 'MEDALS', 110, 0),
-- Vehicle
('M-102 Fast Recon Vehicle', 'M-102_Fast_Recon_Vehicle_Stratagem_Icon.webp', 'VEHICLE', 'REQUISITION_SLIPS', 25000, 25),
('EXO-45 Patriot Exosuit', 'EXO-45_Patriot_Exosuit_Stratagem_Icon.webp', 'VEHICLE', 'REQUISITION_SLIPS', 20000, 25),
('EXO-49 Emancipator Exosuit', 'EXO-49_Emancipator_Exosuit_Stratagem_Icon.webp', 'VEHICLE', 'REQUISITION_SLIPS', 20000, 25);
